name = "simple-times"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "simple-times"
migrations_dir = "./prisma/migrations"
database_id = "377e53d4-7ba0-4ae6-87f3-9dd5508bfcff"